solver:
  class_path: src.CombOptNet.src.ilp.CombOptNet
  init_args:
    vtype: 'B'
    env:
      class_path: gurobi.Env
      init_args:
        params:
          OutputFlag: 0
          TimeLimit: 10
    num_workers: 10
    show_tqdm: True
dataset_dirs: 
#- '/home/cse/phd/csz178057/hpcscratch/comboptnet/synthetic_data/set_covering'
  - '/home/cse/phd/csz178057/hpcscratch/comboptnet/synthetic_data/random_const/binary'
  - '/home/cse/phd/csz178057/hpcscratch/comboptnet/synthetic_data/random_const/dense'
