seed_everything: 42

data:
  class_path: src.datasets.SudokuDataModule
  init_args:
    data_path: data/sudoku_3x3_1M.pt.backup
    collate_fn: src.rrn_utils.collate_sudoku_graph
    splits:
      train: 10000
      val: 1000
      test: 1000
    num_validate_train: 10
    batch_sizes:
      train: 10
      val: 100
      test: 100
    num_workers: 0

model:
  class_path: src.neural_models.SudokuNNModel
  init_args:
    num_classes: 9
    x_key: query/bit
    y_key: target/bit
    c_encoder:
      class_path: src.encoders.SymSudokuCEncoderForRRN
      init_args:
        num_classes: 9
    network:
      class_path:  src.neural_models.SudokuNN
      init_args:
        num_steps: 32 
        embed_size: 16
        hidden_dim: 96
        edge_drop: 0.1
        num_classes: 9 

    optimizer:
      class_path: torch.optim.AdamW
      init_args:
        lr: 1.0e-3
        weight_decay: 1.0e-4

    lr_scheduler:
      # class_path: torch.optim.lr_scheduler.CyclicLR
      # init_args:
      #   base_lr: 0.0
      #   max_lr: 1.0e-3
      #   step_size_up: 1000
      #   cycle_momentum: false
      # config:
      #   interval: step

      #class_path: torch.optim.lr_scheduler.ExponentialLR
      #init_args:
      #  gamma: 1.0

      class_path: torch.optim.lr_scheduler.ReduceLROnPlateau
      init_args:
        mode: max
        factor: 0.2
        patience: 8
        min_lr: 4.0e-5
      config:
        monitor: val/acc/all
        interval: epoch

    schedulers:
      "temp":
        class_path: torch.optim.lr_scheduler.ExponentialLR
        init_args:
          gamma: 1.0

        # class_path: torch.optim.lr_scheduler.ReduceLROnPlateau
        # init_args:
        #   mode: max
        #   factor: 0.1
        #   patience: 1000
        # config:
        #   monitor: acc
        #   interval: step
        # init: 1.0

skip_initial_validation: True
trainer:
  max_epochs: 100
  callbacks:
  - class_path: pytorch_lightning.callbacks.EarlyStopping
    init_args:
      monitor: val/acc/all
      patience: 18
      mode: max
  - class_path: pytorch_lightning.callbacks.ModelSummary
    init_args:
      max_depth: -1
  - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    init_args:
      logging_interval: step
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      monitor: 'val/acc/all'
      mode: 'max'
      filename: best

  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      save_last: True
      save_on_train_epoch_end: True

  log_every_n_steps: 10
  check_val_every_n_epoch: 1
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: neurips_run/sudoku/rrn/
      name: sym3x3_reducelronplateau
      default_hp_metric: false
  gradient_clip_val: 5.0
  gpus: 1
  auto_select_gpus: true
  #precision: 16
  num_sanity_val_steps: 0
  reload_dataloaders_every_n_epochs: 0
  # detect_anomaly: true
