
cross_product_params:
    #  - name: ${data_path}
    #    values: ['data/vis_sudoku/sudoku_2x2_1M.pt']
    #    #values: ['data/vis_sudoku/sudoku_2x3_11214.pt']
    #    short_name: 'd'
    #    create_dir: true
  - name: '${model_seed}' 
    values: [94719,718]
    short_name: 'ms'


param_groups:
    #fn_name: default_read_out
    fn_name: extract_values_from_path  
    init_args:
      source_dir:  '/home/cse/phd/csz178057/hpcscratch/comboptnet/comboptnet-data-in-our-format/datasets/static_constraints'
      factors: [1,2,4]  
    # 
    short_names: ['','t','n','gt','m','ds','']
    names: ['${data_path}', '${task}', '${num_vars}', '${num_gt_constrs}','${num_constrs}', '${data_seed}','${logger_dir}']
    create_dirs: [false,false,false,false,false,false,true]
              
order:  true

config_files:
 - '../conf/templates/con.yaml'
   # - '../conf/tmp/vis_sudoku/templates/nbr_ce.yaml'
   # - '../conf/tmp/vis_sudoku/templates/nbr_margin.yaml'
   # - '../conf/tmp/vis_sudoku/templates/proj_ce.yaml'
   # - '../conf/tmp/vis_sudoku/templates/proj_margin.yaml'

parse_value_fns:
    ${data_path}: extract_sudoku_size
